#!/bin/bash

cd ./flavours/sauce
rm -rf strider-docker-shim
git clone git@github.com:BrowserSwarm/strider-docker-shim.git
cd strider-docker-shim
rm -rf .git
npm install --production
cd ..

rm -rf ../nodejs/strider-docker-shim
cp -R ./strider-docker-shim ../nodejs/
docker build -t browserswarm/sauce .

cd ../nodejs
docker build -t browserswarm/node .

